### ISSUE TITLE
Permanently deactivate this background location display 

### ISSUE THREAD

**Issue by amarradi** [TylerWilliamson/QuickWeather#155]
Is it possible to permanently deactivate this display of the location after I have made the settings? This setting appears after every restart. This is very annoying 

![Screenshot_20240422-065529.png](https://github.com/TylerWilliamson/QuickWeather/assets/720573/a60dde29-e30d-43d2-90d8-bababe881c0c)

**Comment by TylerWilliamson** [comment]
You are seeing this notice because your active location is "My Location" (Standort), which is the current location of the device, as reported by the GPS, and you have enabled a background service, either notifications or the Gadgetbridge extension. In order for the background service to get your current location from the GPS, a special "background location" permission is required which cannot be requested at the same time as the regular location permission on newer Android versions. This message opens a dialog to show you how to grant the permission.

If you want the message to go away, you should either: 
a. grant the background location permission
b. use a fixed location
c. disable the background services

**Comment by amarradi** [comment]
Hey, thanks for the explanations. I have now defined my location and deactivated GPS location detection.
