### ISSUE TITLE
Group weather warnings

### ISSUE THREAD

**Issue by Donkey-Doug** [TylerWilliamson/QuickWeather#16]
I suggest grouping warning of the weather. The group can be selected to provide more detailed info.

This is what it looks like currently:
![Screenshot_20210725-112358_QuickWeather](https://user-images.githubusercontent.com/50382414/126894316-f410fcfb-b1e4-4879-af21-3d7c41a30508.png)

**Comment by TylerWilliamson** [comment]
Currently there are two "Moderate thunderstorm warning" alerts sent by your local weather agency in your area which last until different times. These may or may not refer to the same storm. In order to reduce confusion and offer an abundance of caution, I will not be grouping the alerts together in the app. Please note the alert notifications already group together
