### ISSUE TITLE
DNS lookup fails frequently

### ISSUE THREAD

**Issue by ghost** [TylerWilliamson/QuickWeather#162]
The DNS resolution seems to fail frequently recently. When I take the phone out of my pocket I'm greeted with the notification below. I've started to notice this on my vacation but the same keeps happening at home. I don't notice such issues with other apps or connectivity problems. The reports are being updated so it seems to be an intermittent issue.
My API key is compatible with the Call API 3.0 because I subscribed for free. I have uninstalled und reinstalled the app via F-Droid. (Version 2.6.10)

I'm not using any VPN but the Android Private DNS feature (dns.quad9.net) in case it matters. I believe the error even occurs when I change the provider to Open-Meteo but I have to verify this again to be sure.

Error Obtaining Weather
HTTP: I/O Error: Unable to resolve host "api.openweathermap.org": No address associated with hostname

**Comment by TylerWilliamson** [comment]
I would assume that the Android Private DNS is to blame, but I will have to test to confirm.

**Comment by TylerWilliamson** [comment]
Not a problem, glad the issue resolved itself!

**Comment by huuhaa** [comment]
Actually this issue still exists. Only difference is that I use open-meteo, so at notification address is "api.open-meteo.com". 

I have disabled private DNS, but I do use TrackerControl which by default uses Quad9. TrackerControl reports like should, that it doesn't find any trackers on app, but also hasn't blocked any connection from app. At traffic log of TrackerControl all connections of QuickWeather are allowed, so that shouldn't cause that similar notification mentioned at original issue.
