### ISSUE TITLE
Feature request: auto start on boot

### ISSUE THREAD

**Issue by sbe-arg** [TylerWilliamson/QuickWeather#164]
Autostart option

**Comment by TylerWilliamson** [comment]
QuickWeather already has part of this functionality. It will start up when it receives "BOOT_COMPLETED", which is sent by most devices on most startups. I have discovered there is also "QUICKBOOT_POWERON" which some devices use when a phone is rebooted instead of powered off and powered on. I will add this.

**Comment by TylerWilliamson** [comment]
Fixed in [2.6.11](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.6.11)
