### ISSUE TITLE
System time zone

### ISSUE THREAD

**Issue by Donkey-Doug** [TylerWilliamson/QuickWeather#17]
Please use the system time zone. Now it says "GMT+"

![Screenshot_20210725-112358_QuickWeather_1](https://user-images.githubusercontent.com/50382414/126894343-8ba9b0e0-0bb6-4a89-94fb-aae2b3aa4953.png)

**Comment by TylerWilliamson** [comment]
The timezone is taken from the API result in order to display the weather alerts using the local time. OpenWeatherMap does not seem to be correctly applying "Daylight Savings Time" or "Summer Time". I will not be able to resolve this issue in QuickWeather and this issue should be taken up with [OpenWeatherMap](https://home.openweathermap.org/questions).

![image](https://user-images.githubusercontent.com/8985022/126903812-7062a821-ed17-4e79-8651-f2c7c2dadf3d.png)

**Comment by TylerWilliamson** [comment]
While researching another issue, I determined that this issue is due partly to the language settings on the device. "GMT+02:00" is incorrect, but how the "English (United States)" language represents the "Europe/Amsterdam" timezone. If the language is instead set to "English (Netherlands)", it correctly shows the timezone as "CEST". I will look into a system to generate a Locale based on the language and country of the device at a later time

**Comment by TylerWilliamson** [comment]
I realized that the current timezone for the Netherlands, CEST, is in fact 2 hours ahead of UTC, which is GMT+02:00. There is no issue with QuickWeather nor with OpenWeatherMap. You may wish to look into your language settings on your device. I may look into a system to generate a Locale based on the language and country of the device at a later time
