### ISSUE TITLE
Mismatch between current state if town selected manually and by location sharing

### ISSUE THREAD

**Issue by devdan** [TylerWilliamson/QuickWeather#171]
There is a big mismatch between the temperatures of the nearest town and the location near that town.
Please see screenshots.
![IMG_20240812_173231](https://github.com/user-attachments/assets/a35682a9-3d8c-4f91-bd38-4c97427611cb)
![IMG_20240812_173213](https://github.com/user-attachments/assets/7c95c0b0-ee25-495e-a179-5f2b6a34e23e)

**Comment by devdan** [comment]
Provider is open-meteo.

**Comment by TylerWilliamson** [comment]
This is not a bug in QuickWeather. QuickWeather just displays the weather data from the provider. The difference in temperature of those locations could be due to either a) a real difference in temperature, b) the temperature being from two different weather probes, or c) some issue with how open-meteo interprets/models the temperature at those points

If you feel there is an issue with the data coming from open-meteo, I would suggest opening a ticket on their GitHub

**Comment by devdan** [comment]
Thanks! I'm going to create an issue at open-meteo.
