### ISSUE TITLE
HTTP I/O Error

### ISSUE THREAD

**Issue by amarradi** [TylerWilliamson/QuickWeather#175]
The following error has been appearing in my app since this morning

![Screenshot_20240830-155828.png](https://github.com/user-attachments/assets/4dc482df-bfdb-4565-83a1-61a9e7d41248)

**Comment by TylerWilliamson** [comment]
That appears to be a network issue, which may be due to:
1. The app being "optimized" or put to sleep or otherwise denied internet by your OS
2. Your connection to your network (I.E. wifi) might have gone down momentarily
3. Your network itself (like the ISP) may had a temporary issue
4. Open-Meteo could have gone down momentarily

In any event, that error is there to tell you that the current weather could not be obtained at that time and for you to act accordingly. If you would rather not see the error messages, they are in a separate notification channel and can be disabled

This is expected behavior and not a bug in QuickWeather
