### ISSUE TITLE
App doesn't respect safe areas

### ISSUE THREAD

**Issue by teoAlivanoglou** [TylerWilliamson/QuickWeather#184]
Using Android 15 on a Google pixel 7.

Appbar draws on behind the phone's status bar.

![Screenshot_20241018-170340](https://github.com/user-attachments/assets/43cc0a48-d1b0-42a0-848e-f362bbcd57eb)

**Comment by TylerWilliamson** [comment]
I just tried to replicate this issue with an Android Virtual Device running Android 15, but I was unable to replicate it. The toolbar is in the correct location on my virtual device. Do you have any settings changed that might affect it? Immersive mode, etc? I see that you are using the 3-button navigation, but when I enable that, I still cannot replicate this issue

**Comment by TylerWilliamson** [comment]
In doing more research, this may be due to the ["edge-to-edge" feature of Android 15](https://developer.android.com/develop/ui/views/layout/edge-to-edge). I will investigate why my virtual device isn't able to replicate the issue and see what I can do to address this in a future release

**Comment by teoAlivanoglou** [comment]
> I just tried to replicate this issue with an Android Virtual Device running Android 15, but I was unable to replicate it. The toolbar is in the correct location on my virtual device. Do you have any settings changed that might affect it? Immersive mode, etc? I see that you are using the 3-button navigation, but when I enable that, I still cannot replicate this issue

I enabled 3-button to check the hamburger menu because gesture navigation was too annoying when I tried to open it.  Otherwise I haven't changed anything

**Comment by TylerWilliamson** [comment]
This issue should be resolved in [2.7.4](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.7.4). I am still having trouble changing the navigation bar button colors when using the 3-button navigation, but I wanted to push out this fix. Please let me know if you see any other issues in Android 15. I have not yet had an opportunity to fully test things in that version

To users on previous versions of Android, the fix for this issue may cause issues for you. If you encounter any weird spacing or layout issues, please leave a comment on this issue.

I plan to close this in a week or two if there are no followup issues, but I do not mind re-opening if needed.
