### ISSUE TITLE
Frequent notifications for same weather alert

### ISSUE THREAD

**Issue by ryester27** [TylerWilliamson/QuickWeather#27]
Hello. I've noticed that the same weather alert pops up in my notifications every 30 minutes or so if I keep clearing it out in the notification drawer. Considering the expiration time on these alerts can be hours into the future, it can get rather annoying being notified for the same alert constantly.

Some options to resolve:
1) Make the weather alert notification persistent so they can't be cleared out
2) Add logic so that it keeps track of the last weather alert, and doesn't notify the user again if the same alert is pushed by the weather service again during its duration

**Comment by TylerWilliamson** [comment]
That logic already exists in the app. When you see the "same" alert multiple times, it is typically due to the expiration time being updated. In order to update the expiration time, the weather station actually sends out additional alerts with the same title and similar descriptions with the updated expiration time. If you see this happen again, please make note of the expiration time of the alert (screenshots preferred) and add them to this issue and I will re-open.

**Comment by TylerWilliamson** [comment]
I should not have been so quick to dismiss this bug. I am experiencing it myself now and I will investigate it

**Comment by TylerWilliamson** [comment]
This issue should be resolved in [QuickWeather-2.1.0](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.1.0), which is available on GitHub, or in Beta on the Google Play Store. Please let me know if you still encounter this bug on the new version. I plan to continue testing and fully release this version on the Google Play Store in a few days.
