### ISSUE TITLE
Add more info to notification

### ISSUE THREAD

**Issue by xeruf** [TylerWilliamson/QuickWeather#28]
Right now, the ongoing notification is very sparse and the way it is displayed even a little annoying at times, making you interact just to get the temperature:
![image](https://user-images.githubusercontent.com/13354331/156733186-00849166-9164-410f-af86-546e32d21e55.png)

Again, I encourage to have a look at Weawow, which has lots of details for widgets and notifications, just unfortunately is not open.

**Comment by TylerWilliamson** [comment]
What device are you using? The notification should show the temperature and not cut off like that when collapsed or expanded

![Screenshot_20220310-192818](https://user-images.githubusercontent.com/8985022/157778363-e676f4fd-36f7-4433-8708-0610e54cc1af.png)
![Screenshot_20220310-192844](https://user-images.githubusercontent.com/8985022/157778367-6ce57591-804b-42e3-90b0-b210bcff1660.png)

**Comment by xeruf** [comment]
Honor 20, it was on the phone of my mom, so I also won't be able to test as frequently ^^
On my Samsung Galaxy S7 it actually looks fine

**Comment by TylerWilliamson** [comment]
I believe the issue that your mom encountered was due to the notification not being minimized for some reason. If you look at your screenshot, it has the down arrow \\/ icon on the top right, indicating that the notification can be expanded. Please go into the Notification Settings for QuickWeather, open the "Current Weather" category, and ensure that the "Minimize notifications" setting is enabled.

**Comment by xeruf** [comment]
thank you - but regardless, the information is very sparse and not cached, which is why I personally use https://github.com/WangDaYeeeeee/GeometricWeather now :)
