### ISSUE TITLE
Graph sometimes not intelligible

### ISSUE THREAD

**Issue by cloo** [TylerWilliamson/QuickWeather#33]
![Screenshot_20220714-223834__01](https://user-images.githubusercontent.com/651760/179161737-1f820d73-a040-4948-97a6-b7620408360e.jpg)

Does the graph show fluctuation between 16 and 16 degrees? If so, aligning graph and number precision in decimal places would help: graph should take into account only changes in whole degrees, or in decimal degrees, so that it could be understood.

**Comment by TylerWilliamson** [comment]
I'd call this primarily an edge case, but I think I have a solution. Currently both the minimum and maximum temperatures are rounded using "floor". I.E. the minimum and maximum may be 16.1 and 16.8, but both round to 16. I plan to always round the minimum temperature down and the maximum up (so it would be 16 and 17), and for each temperature point, round to the nearest 0.1. This should make it understandable in all instances.

Are stable temperatures common at this location? Would you mind sharing the location so that I may test using it?

**Comment by cloo** [comment]
Thanks @TylerWilliamson 
Stable temperatures are quite uncommon in [that location](https://www.openstreetmap.org/node/32445757#map=14/55.3709/21.0626&layers=CN), maybe therefore I got confused :) 
Other option, which might be more natural to read (but probably harder to implement), is to compress the graph gradually towards a line, in cases when the temperature fluctuation is very low, say, 3 degrees or less.

**Comment by TylerWilliamson** [comment]
Fixed in [2.2.1](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.2.1)
