### ISSUE TITLE
API key doesn't work

### ISSUE THREAD

**Issue by Ilav1** [TylerWilliamson/QuickWeather#36]
I created an OWM account over (link in the app).
24h later the Key is still not working with the app. OWM support said, that the key is activated and can be used. So there has to be a problem with the app. I got the same problem in other weather apps too. So maybe there is something chanced by OWM?

How to Reproduce

1. Start the App
2. Enter API Key on the second page
3. Test API key
4. The app is loading a long time
5. Error Key is invalid

App version: 5.5
Android version: 10
Device: Huawei P Smart 2019

**Comment by TylerWilliamson** [comment]
If the API key is not working in other apps either, I would assume it's the API key. 

Try this...

1. Go to your OpenWeatherMap and copy the API key from [here](https://home.openweathermap.org/api_keys). Do not rely on any saved API key (in case of a typo, etc)
2. Use that API key with this URL - https://api.openweathermap.org/data/2.5/onecall?appid=YOUR_API_KEY&lat=33.749&lon=-84.388&lang=en-US&units=imperial
3. You should get the current weather for Atlanta. If you get an error about "Invalid API Key", then there is some issue with your API key. You can generate a new API key if needed.

**Comment by Ilav1** [comment]
Hi,

my key is invalid with this link.

I also contacted other app developers with this problem because the key is working fine.

Maybe your take a look at these issue:

https://github.com/woheller69/weather/issues/62#issuecomment-1219545824

Woheller knows that OWM changed something with the subscription plan so there is to change something in the app. Otherwise new user won't be able to use the apps with the new keys :(

**Comment by TylerWilliamson** [comment]
Looking at the other thread, this seems to be because you do not seem to be able to use the "onecall" API, which is the main API that QuickWeather uses. What OpenWeatherMap subscription do you have? "Free"? Have you entered billing info in OpenWeatherMap? As long as you stay under 1000 calls per day you will not be billed on the Free plan

**Comment by Ilav1** [comment]
Yes, I have the free subscription.
When there is no other option than spreading the billing details, I thing new users will not use app like this.

You also have to tell new users that they have to subscribe the option and have to fill the billing details to OWM in order to use your app.

Why are we using open source?
To own our data without spreading theme.

I think OWM is changing there subscription plan maybe because of capitalism thing.

**Comment by TylerWilliamson** [comment]
Unfortunately, your issue seems to be with OpenWeatherMap, not QuickWeather. QuickWeather requires using OpenWeatherMap's "onecall" API, which requires that you enter billing info. It is highly unlikely that you would use more than 1000 API calls in a day for a single user. QuickWeather caches the weather data for 1 minute for each location, so to use more than 1000 API calls you would need to constantly switch locations and refresh the weather.

Also, this subscription strategy is not unique to OpenWeatherMap. If you want to avoid giving out your credit/debit information, you can most likely use a pre-paid debit card (gift card).

Since there is no issue with QuickWeather, I will be closing this.

**Comment by TylerWilliamson** [comment]
This issue may be the same as #41 and I am continuing to investigate it there. This issue will remain closed
