### ISSUE TITLE
Allow to add/remove locations from the side bar

### ISSUE THREAD

**Issue by new2f7** [TylerWilliamson/QuickWeather#67]
The settings menu is fine for first time setup but not for frequent changing of locations (i.e. while travelling).

**Comment by TylerWilliamson** [comment]
This is a good idea and a common request. I'll need to think about the best UX solution to accomplish this.

**Comment by TylerWilliamson** [comment]
The solution I came up with is to add an "edit" icon to the locations in the sidebar, clicking it will bring you to the "Locations" tab of settings. This solution is in version [2.3.5](https://github.com/TylerWilliamson/QuickWeather/releases/tag/2.3.5). I think this should be the best UX solution, instead of a pop-up dialog box or some custom UI in the sidebar. Please let me know what you think. For now, I will close this ticket

**Comment by new2f7** [comment]
It looks great, thank you very much.
