### ISSUE TITLE
Cannot add manual location

### ISSUE THREAD

**Issue by Donkey-Doug** [TylerWilliamson/QuickWeather#9]
I would like to manually select "other location", but I cannot search. It seems like a textfield without functionality.

**Comment by TylerWilliamson** [comment]
The searchbox looks up cities, states, and countries which appear in a dropdown. If you cannot see this functionality, please respond with your device, android version, and any other relevant details and I will attempt to replicate the issue. If you do not respond within 7 days I will close this issue

**Comment by Donkey-Doug** [comment]
Video:

https://user-images.githubusercontent.com/50382414/126894125-70e6029c-248f-4fca-ba1a-1d037d47268d.mp4

Device: Xiaomi Mi 9T Pro
Android: Android 10 (lineageos without google play services)

**Comment by TylerWilliamson** [comment]
This functionality currently makes use of a Google Geocoder API. This functionality is likely unavailable on devices without Google Play Services. I will likely not be able to provide address auto-completion for these devices. However, I should be able to add a manual input form. You will need the coordinates of the location you wish to add (these will automatically be rounded to 1 decimal place).

Since this is preventing your use of the app, I will try to get this feature added next release. This feature will tie in nicely with #6

**Comment by TylerWilliamson** [comment]
Also, I have deleted your comment since your video exposes your API Key. I would recommend regenerating your API Key [here](https://home.openweathermap.org/api_keys).

I have copied your device details below
> Device: Xiaomi Mi 9T Pro
> Android: Android 10 (lineageos without google play services)

**Comment by Donkey-Doug** [comment]
Is an api key sensitive info? Thank you though.

**Comment by Donkey-Doug** [comment]
How do other open source weather app select locations? This limitation is only present in quickweather.

**Comment by TylerWilliamson** [comment]
API Keys are sensitive information and can be used maliciously. You should keep your API Key private.

This limitation was only present on devices without Google Play Services as you are unable to use the Geocoder.

I have resolved this issue in [1.3.3](https://github.com/TylerWilliamson/QuickWeather/releases/tag/1.3.3). You can manually enter a location by clicking "Manual" and entering the location name, latitude, and longitude.
