### ISSUE TITLE
Quick Weather underreporting wind speeds

### ISSUE THREAD

**Issue by Spark-albus** [TylerWilliamson/QuickWeather#91]
Hello, while using quick weather to forward data to Gadgetbridge, I found wind speeds to be under reported (11.3 km/h) compared to other internet weather sites (28.8 km/h) (see attachments) for the same location. I noticed this because it is quite windy outside (gusts up to 50.4 km/h around the time of concern) and decided to check the app. Anyone familiar with this?
![1000021594](https://github.com/TylerWilliamson/QuickWeather/assets/58271463/622f9f2f-997e-460a-b0af-ae795aea50ba)
![1000021593](https://github.com/TylerWilliamson/QuickWeather/assets/58271463/4df4fee1-40ae-48f6-8cf0-1ff45cf99e77)

**Comment by TylerWilliamson** [comment]
Are you using OpenWeatherMap or Open-Meteo for your weather provider in QuickWeather? Either way, this is likely because the wind speed depends on the elevation that it is measured at. Open-Meteo measures at 10m height, for example. I am unsure at what height OpenWeatherMap measures or "Weerplaza". Alternatively, this may be a difference between (sustained) wind speed and wind gust.

In summary, this doesn't seem like a QuickWeather issue, but either a weather provider issue or a difference in measurement between weather providers

**Comment by TylerWilliamson** [comment]
Ugh. This is actually a bug. I've been assuming the OpenWeatherMap data is mph since internally I use imperial units, but apparently OpenWeatherMap return m/s by default. I'll fix this for next minor version.

**Comment by Spark-albus** [comment]
Thank you very much for your quick response. I use othe OpenWeatherMap API in combination with Quick Weather. Looking forward to the update.

**Comment by TylerWilliamson** [comment]
@Spark-albus I re-ran my tests and now I am seeing the same values in OpenWeatherMap API as well as QuickWeather. I believe my earlier tests were in error. I did confirm that QuickWeather is internally using mph for the wind speed, then reporting it to the user as whatever unit they chose, so that isn't the issue.

It appears that the issue is that OpenWeatherMap is simply reporting a much lower wind speed than any other weather provider. As a quick test, I checked AccuWeather, Weather.com, and Google and they all had similar wind speeds to Open-Meteo (approximately 15-20mph). OpenWeatherMap meanwhile showed 2mph.

Unfortunately, I do not think there is anything that QuickWeather can do to fix this, and so I will be leaving this closed. 

You could use Open-Meteo as your weather provider to get more accurate wind speeds, but be aware that there are differences in the data returned from the providers, including the lack of weather alerts. See [this comment](https://github.com/TylerWilliamson/QuickWeather/issues/75#issuecomment-1714781263) for more information
